export const API_CONFIG = {
  BASE_URL: 'https://alashcloud.kz',
  TIMEOUT: 30000,
  HEADERS: {
    'Content-Type': 'application/x-www-form-urlencoded',
  },
};

export const API_ENDPOINTS = {
  LOGIN: '/go/login',
  LOGOUT: '/logout',
  USERS_LIST: '/go/users/list',
  USERS_CREATE: '/go/users',
  USERS_EDIT: '/go/users/edit',
  USERS_DELETE: '/go/users/delete',
  ACCOUNTS_GET: '/go/accounts',
  ACCOUNTS_CREATE: '/go/accounts',
  ACCOUNTS_EDIT: '/go/accounts/edit',
  ACCOUNTS_DELETE: '/go/accounts/delete',
  DEVICES_LIST: '/go/devices',
  DEVICES_CREATE: '/go/devices/add',
  DEVICES_UPDATE: '/go/devices/edit',
  DEVICES_DELETE: '/go/devices/delete',
  DEVICES_MACHID_GENERATE: '/go/machid/generate',
  DEVICES_PRODUCTS: '/go/devices',
  DEVICES_AVAILABLE_PRODUCTS: '/go/devices',
  DEVICES_ASSIGN_PRODUCTS: '/go/devices',
  INVOICES_LIST: '/go/invoices/list',
  INVOICES_CREATE: '/go/invoices',
  INVOICES_EDIT: '/go/invoices/edit',
  INVOICES_DELETE: '/go/invoices/delete',
  INVOICE_PRODUCTS_GET: '/go/invoices',
  INVOICE_PRODUCTS_CREATE: '/go/invoices/products',
  INVOICE_PRODUCTS_EDIT: '/go/invoices/products/edit',
  INVOICE_PRODUCTS_DELETE: '/go/invoices/products/delete',
  UPLOAD_IMAGE: '/go/upload/image',
  WAREHOUSE_UPLOAD_IMAGE: '/go/warehouse/upload/image',
  CATEGORIES: '/go/categories',
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  VALIDATION_ERROR: 422,
  SERVER_ERROR: 500,
};
